In [289]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [290]:
space_df = pd.read_csv("data/Master_Space_Data_All.txt")
space_df.head()

,Company Name,Location,Datum,Detail,Status Rocket,Price,Status Mission
0,SpaceX,"SLC-4E, Vandenberg SFB, CA",Feb 25 2026 14:12 UTC,Falcon 9 Block 5 | Starlink Group 17-26,StatusActive,52.0,Success
1,SpaceX,"SLC-40, Cape Canaveral SFS, FL",Feb 24 2026 23:04 UTC,Falcon 9 Block 5 | Starlink Group 6-110,StatusActive,52.0,Success
2,SpaceX,"SLC-4E, Vandenberg SFB, CA",Feb 21 2026 13:42 UTC,Falcon 9 Block 5 | Starlink Group 11-5,StatusActive,52.0,Success
3,CASC,"Xichang Satellite Launch Center, China",Feb 21 2026 09:30 UTC,Long March 2C | Geely-03 Group 01,StatusActive,30.0,Success
4,SpaceX,"SLC-40, Cape Canaveral SFS, FL",Feb 19 2026 10:48 UTC,Falcon 9 Block 5 | Starlink Group 6-109,StatusActive,52.0,Success

In [291]:
space_df['Price'] = pd.to_numeric(space_df['Price'].astype(str).str.replace(',', ''), errors='coerce')

In [292]:
space_df['Price'] = space_df['Price'].fillna(0).astype(float)

In [293]:
space_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5319 entries, 0 to 5318
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company Name    5319 non-null   object
 1   Location        5319 non-null   object
 2   Datum           5319 non-null   object
 3   Detail          5318 non-null   object
 4   Status Rocket   5316 non-null   object
 5   Price           5319 non-null   float64
 6   Status Mission  5315 non-null   object
dtypes: float64(1), object(6)
memory usage: 291.0+ KB

In [294]:
print(space_df.columns)

Index(['Company Name', 'Location', 'Datum', 'Detail', 'Status Rocket', 'Price',
       'Status Mission'],
      dtype='object')

In [295]:
space_df['countries'] = space_df['Location'].str.split(',').str[-1].str.strip()

In [296]:
usa_states = ['CA', 'FL', 'TX', 'Texas', 'New Mexico', 'Virginia']
space_df['countries'] = space_df['countries'].replace(usa_states, 'USA')

In [297]:
print(space_df[['Location', 'countries']].head())

                                 Location countries
0              SLC-4E, Vandenberg SFB, CA       USA
1          SLC-40, Cape Canaveral SFS, FL       USA
2              SLC-4E, Vandenberg SFB, CA       USA
3  Xichang Satellite Launch Center, China     China
4          SLC-40, Cape Canaveral SFS, FL       USA

In [298]:
space_df.sample()

,Company Name,Location,Datum,Detail,Status Rocket,Price,Status Mission,countries
1937,Eurockot,"Site 133/3, Plesetsk Cosmodrome, Russia","Sat Oct 08, 2005 15:02 UTC",Rokot/Briz KM | CryoSat-1,StatusRetired,41.0,Failure,Russia

In [299]:
space_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5319 entries, 0 to 5318
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company Name    5319 non-null   object
 1   Location        5319 non-null   object
 2   Datum           5319 non-null   object
 3   Detail          5318 non-null   object
 4   Status Rocket   5316 non-null   object
 5   Price           5319 non-null   float64
 6   Status Mission  5315 non-null   object
 7   countries       5319 non-null   object
dtypes: float64(1), object(7)
memory usage: 332.6+ KB

In [300]:
# space_df['Date'] = pd.to_datetime(space_df['Datum'], errors='coerce', utc=True).dt.year

In [301]:
def extract_year(text):
    if pd.isna(text):
        return None
    match = re.search(r'(19\d{2}|20\d{2})', str(text))
    return int(match.group(1)) if match else None

space_df['date'] = space_df['Datum'].apply(extract_year)

In [304]:
space_df.sample(50)

,Company Name,Location,Datum,Detail,Status Rocket,Price,Status Mission,countries,date
4419,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 09, 1970 11:04 UTC",Voskhod | Cosmos 370,StatusRetired,0.0,Success,Kazakhstan,1970.0
4758,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia","Mon Jun 12, 1967 18:06 UTC",Cosmos-2I (63SM) | Cosmos 165,StatusRetired,0.0,Success,Russia,1967.0
3975,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Mon Dec 02, 1974 09:40 UTC",Soyuz U | Soyuz 16,StatusRetired,0.0,Success,Kazakhstan,1974.0
2932,RVSN USSR,"Site 132/1, Plesetsk Cosmodrome, Russia","Thu Jul 14, 1988 11:40 UTC",Cosmos-3M (11K65M) | Cosmos 1958,StatusRetired,0.0,Success,Russia,1988.0
5126,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sat Sep 01, 1962 02:12 UTC",Molniya | 2MV-1 n†­2 (Venera 2),StatusRetired,0.0,Failure,Kazakhstan,1962.0
2601,Martin Marietta,"SLC-4W, Vandenberg AFB, California, USA","Tue Oct 05, 1993 17:56 UTC",Titan II(23)G | Landsat 6,StatusRetired,35.0,Failure,USA,1993.0
70,SpaceX,"Vandenberg, USA",Dec 07 2025 11:30 UTC,Falcon 9 Block 5 | Starlink Group 11-15,StatusActive,52.0,Success,USA,2025.0
2380,Boeing,"SLC-17A, Cape Canaveral AFS, Florida, USA","Tue May 20, 1997 22:39 UTC",Delta II 7925 | Telenor Thor II,StatusRetired,0.0,Success,USA,1997.0
595,Amazon/ULA,"SLC-41, Cape Canaveral, FL",Oct 06 2023 18:06 UTC,Atlas V 501 | Project Kuiper (Protoflight),StatusRetired,132.0,Success,USA,2023.0
2235,NASA,"LC-39B, Kennedy Space Center, Florida, USA","Fri Jul 23, 1999 04:31 UTC",Space Shuttle Columbia | STS-93,StatusRetired,450.0,Success,USA,1999.0
3971,RVSN USSR,"Site 132/1, Plesetsk Cosmodrome, Russia","Wed Dec 18, 1974 14:12 UTC",Cosmos-3M (11K65M) | Cosmos 698,StatusRetired,0.0,Success,Russia,1974.0
935,SpaceX,"LC-39A, Kennedy Space Center, FL, USA",Apr 23 2021 09:49 UTC,Falcon 9 Block 5 | Crew-2 (Endeavour),StatusActive,145.0,Success,USA,2021.0
150,SpaceX,"Vandenberg, USA",Sep 22 2025 11:45 UTC,Falcon 9 Block 5 | NROL-48,StatusActive,62.0,Success,USA,2025.0
3241,RVSN USSR,"Site 107/1, Kapustin Yar, Russia","Wed Aug 31, 1983 06:30 UTC",Cosmos-3M (11K65M) | Cosmos 1494,StatusRetired,0.0,Success,Russia,1983.0
4885,RVSN USSR,"Site 31/6, Baikonur Cosmodrome, Kazakhstan","Thu Mar 31, 1966 10:48 UTC",Molniya-M /Block L | Luna 10,StatusRetired,0.0,Success,Kazakhstan,1966.0
1348,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Mon May 15, 2017 23:21 UTC",Falcon 9 Block 3 | Inmarsat-5 F4,StatusRetired,62.0,Success,USA,2017.0
2377,Arianespace,"ELA-2, Guiana Space Centre, French Guiana, France","Wed Jun 25, 1997 23:44 UTC",Ariane 44P | Intelsat 802,StatusRetired,0.0,Success,France,1997.0
3783,RVSN USSR,"Site 43/3, Plesetsk Cosmodrome, Russia","Thu Aug 12, 1976 13:30 UTC",Soyuz U | Cosmos 848,StatusRetired,0.0,Success,Russia,1976.0
5184,US Air Force,"SLC-17B, Cape Canaveral AFS, Florida, USA","Wed Nov 15, 1961 22:26 UTC",Thor-DM21 Ablestar | Transit 4B & TRAAC,StatusRetired,0.0,Success,USA,1961.0
849,CASC,"LC-2, Jiuquan, China",Dec 10 2021 00:11 UTC,Long March 4B | Shijian 6-05,StatusActive,30.0,Success,China,2021.0
3571,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Fri Jul 14, 1978 15:00 UTC",Molniya-M /Block ML | Molniya-1 n†­75,StatusRetired,0.0,Success,Russia,1978.0
1951,VKS RF,"Site 16/2, Plesetsk Cosmodrome, Russia","Tue Jun 21, 2005 00:48 UTC",Molniya-M /Block ML | Molniya-3K n†­175,StatusRetired,0.0,Failure,Russia,2005.0
4357,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Sat Apr 17, 1971 11:44 UTC",Vostok-2M | Meteor n†­19,StatusRetired,0.0,Success,Russia,1971.0
5186,US Air Force,"SLC-2E (75-1-1), Vandenberg AFB, California, USA","Sun Nov 05, 1961 20:00 UTC",Thor DM-21 Agena-B | Discoverer 34,StatusRetired,0.0,Failure,USA,1961.0
3864,Martin Marietta,"SLC-4E, Vandenberg AFB, California, USA","Thu Dec 04, 1975 20:38 UTC",Titan IIID | KH-9 & S3,StatusRetired,0.0,Success,USA,1975.0
3256,ESA,"ELV-1 (SLV), Guiana Space Centre, French Guian...","Thu Jun 16, 1983 11:59 UTC",Ariane 1 | ECS 1 & Oscar-10,StatusRetired,0.0,Success,France,1983.0
5096,US Air Force,"SLC-5, Vandenberg AFB, California, USA","Wed Dec 19, 1962 01:25 UTC",Scout X-3 | Transit-5A 1,StatusRetired,0.0,Success,USA,1962.0
2658,VKS RF,"Site 43/3, Plesetsk Cosmodrome, Russia","Wed Nov 25, 1992 12:18 UTC",Molniya-M /Block 2BL | Cosmos 2222,StatusRetired,0.0,Success,Russia,1992.0
4096,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Tue Oct 16, 1973 12:00 UTC",Voskhod | Cosmos 600,StatusRetired,0.0,Success,Russia,1973.0
3122,RVSN USSR,"Site 16/2, Plesetsk Cosmodrome, Russia","Tue Jun 18, 1985 00:40 UTC",Molniya-M /Block 2BL | Cosmos 1661,StatusRetired,0.0,Success,Russia,1985.0
4055,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia","Wed Feb 27, 1974 11:05 UTC",Cosmos-2I (63SM) | Cosmos 633,StatusRetired,0.0,Success,Russia,1974.0
10,ULA,"SLC-41, Cape Canaveral SFS, FL",Feb 12 2026 09:22 UTC,Vulcan VC4S | USSF-87 (GSSAP),StatusActive,120.0,Success,USA,2026.0
3769,RVSN USSR,"Site 43/4, Plesetsk Cosmodrome, Russia","Mon Oct 04, 1976 11:00 UTC",Soyuz U | Zenit-4MKT n†­370,StatusRetired,0.0,Failure,Russia,1976.0
2763,RVSN USSR,"Site 43/3, Plesetsk Cosmodrome, Russia","Fri Feb 15, 1991 15:19 UTC",Molniya-M /Block ML | Molniya-1 n†­147,StatusRetired,0.0,Success,Russia,1991.0
2553,VKS RF,"Site 45/1, Baikonur Cosmodrome, Kazakhstan","Fri Aug 26, 1994 12:00 UTC",Zenit-2 | Cosmos 2290,StatusRetired,0.0,Success,Kazakhstan,1994.0
1208,ISRO,"First Launch Pad, Satish Dhawan Space Centre, ...","Sun Sep 16, 2018 16:38 UTC",PSLV-CA | SSTL-1 & NovaSAR-S,StatusActive,21.0,Success,India,2018.0
583,SpaceX,"SLC-4E, Vandenberg, CA, USA",Nov 14 2023 16:35 UTC,Falcon 9 Block 5 | Transporter-9 (Rideshare),StatusActive,52.0,Success,USA,2023.0
696,CASC,"Wenchang, China",Jan 08 2023 22:00 UTC,Long March 7A | Shijian 23,StatusActive,60.0,Success,China,2023.0
783,SpaceX,"SLC-40, Cape Canaveral, FL, USA",Jun 08 2022 21:04 UTC,Falcon 9 Block 5 | Nilesat 301,StatusActive,62.0,Success,USA,2022.0
1860,NASA,"LC-39A, Kennedy Space Center, Florida, USA","Fri Jun 08, 2007 23:38 UTC",Space Shuttle Atlantis | STS-117,StatusRetired,450.0,Success,USA,2007.0
2264,Boeing,"SLC-17B, Cape Canaveral AFS, Florida, USA","Sun Jan 03, 1999 20:21 UTC",Delta II 7425 | Mars Polar Lander,StatusRetired,0.0,Success,USA,1999.0
3713,RVSN USSR,"Site 43/3, Plesetsk Cosmodrome, Russia","Tue Apr 26, 1977 14:45 UTC",Soyuz U | Cosmos 905,StatusRetired,0.0,Success,Russia,1977.0
3337,RVSN USSR,"Site 16/2, Plesetsk Cosmodrome, Russia","Wed Mar 31, 1982 16:27 UTC",Vostok-2M | Cosmos 1346,StatusRetired,0.0,Success,Russia,1982.0
3892,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Tue Sep 09, 1975 00:19 UTC",Molniya-M /Block ML | Molniya-2 n†­53,StatusRetired,0.0,Success,Russia,1975.0
3470,ISAS,"Mu Pad, Uchinoura Space Center, Japan","Sun Feb 17, 1980 00:40 UTC",Mu-III S | Tansei 4,StatusRetired,0.0,Success,Japan,1980.0
1778,ISA,"Imam Khomeini Spaceport, Semnan Space Center, ...","Mon Feb 02, 2009",Safir-1 | Omid,StatusRetired,0.0,Success,Iran,2009.0
1133,Rocket Lab,"Rocket Lab LC-1A, M? hia Peninsula, New Zealand","Sun May 05, 2019 06:00 UTC",Electron/Curie | That's a Funny Looking Cactus,StatusActive,7.0,Success,New Zealand,2019.0
1825,Arianespace,"ELA-3, Guiana Space Centre, French Guiana, France","Sun Mar 09, 2008 04:03 UTC",Ariane 5 ES | Jules Verne ATV,StatusRetired,0.0,Success,France,2008.0
3678,RVSN USSR,"Site 31/6, Baikonur Cosmodrome, Kazakhstan","Wed Jul 20, 1977 07:35 UTC",Soyuz U | Cosmos 932,StatusRetired,0.0,Success,Kazakhstan,1977.0
666,SpaceX,"SLC-40, Cape Canaveral, FL, USA",Mar 17 2023 23:38 UTC,Falcon 9 Block 5 | SES-18 & 19,StatusActive,62.0,Success,USA,2023.0

In [305]:
space_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5319 entries, 0 to 5318
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company Name    5319 non-null   object
 1   Location        5319 non-null   object
 2   Datum           5319 non-null   object
 3   Detail          5318 non-null   object
 4   Status Rocket   5316 non-null   object
 5   Price           5319 non-null   float64
 6   Status Mission  5315 non-null   object
 7   countries       5319 non-null   object
 8   date            5132 non-null   float64
dtypes: float64(2), object(7)
memory usage: 374.1+ KB

In [308]:
space_df['date'] = space_df['date'].astype('Int64')

In [309]:
space_df.head()

,Company Name,Location,Datum,Detail,Status Rocket,Price,Status Mission,countries,date
0,SpaceX,"SLC-4E, Vandenberg SFB, CA",Feb 25 2026 14:12 UTC,Falcon 9 Block 5 | Starlink Group 17-26,StatusActive,52.0,Success,USA,2026
1,SpaceX,"SLC-40, Cape Canaveral SFS, FL",Feb 24 2026 23:04 UTC,Falcon 9 Block 5 | Starlink Group 6-110,StatusActive,52.0,Success,USA,2026
2,SpaceX,"SLC-4E, Vandenberg SFB, CA",Feb 21 2026 13:42 UTC,Falcon 9 Block 5 | Starlink Group 11-5,StatusActive,52.0,Success,USA,2026
3,CASC,"Xichang Satellite Launch Center, China",Feb 21 2026 09:30 UTC,Long March 2C | Geely-03 Group 01,StatusActive,30.0,Success,China,2026
4,SpaceX,"SLC-40, Cape Canaveral SFS, FL",Feb 19 2026 10:48 UTC,Falcon 9 Block 5 | Starlink Group 6-109,StatusActive,52.0,Success,USA,2026